//@ts-ignore
import { createOptions } from "@thisbeyond/solid-select";

export const languagesOptions = [
    "English",
    "French",
    "Italian",
    "German",
    "Spanish - Spain",
    "Japanese",
    "Portuguese - Brazil",
    "Russian",
    "Simplified Chinese",
    "Traditional Chinese",
    "Korean",
    "Portuguese",
    "Danish",
    "Polish",
    "Turkish",
    "Czech",
    "Hungarian",
    "Dutch",
    "Ukrainian",
    "Spanish - Latin America",
    "Arabic",
    "Norwegian",
    "Romanian",
    "Swedish",
    "Thai",
    "Vietnamese",
    "Finnish",
    "Bulgarian",
    "Greek",
    "German;",
    "Slovakian",
    "Portuguese - Portugal",
    "Afrikaans",
    "Amharic",
    "Albanian",
    "Assamese",
    "Azerbaijani",
    "Bangla",
    "Basque",
    "Belarusian",
    "Bosnian",
    "Dari",
    "Indonesian",
    "Armenian",
    "Estonian",
    "Persian",
    "Filipino",
    "Welsh",
    "Galician",
    "Gujarati",
    "Georgian",
    "Hausa",
    "Hindi",
    "Croatian",
    "Kannada",
    "Catalan",
    "Kazakh",
    "K'iche",
    "Khmer",
    "Konkani",
    "Kyrgyz",
    "Latvian",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malayalam",
    "Malay",
    "Maltese",
    "Maori",
    "Marathi",
    "Mongolian",
    "Nepali",
    "Odia",
    "Punjabi (Gurmukhi)",
    "Punjabi (Shahmukhi)",
    "Kinyarwanda",
    "Sinhala",
    "Sindhi",
    "Slovak",
    "Slovenian",
    "Sorani",
    "Sotho",
    "Swahili",
    "Serbian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Tigrinya",
    "Tswana",
    "Turkmen",
    "Urdu",
    "Uyghur",
    "Valencian",
    "Wolof",
    "Xhosa",
    "Yoruba",
    "Zulu",
    "Cherokee",
    "Uzbek",
    "Hebrew",
    "Igbo",
    "Irish",
    "Scots",
    "Icelandic",
    "Quechua"
]

export const languagesProps = createOptions(languagesOptions)